name: CI

on:
  pull_request:
    branches: [master]

jobs:
  depth:
    runs-on: ubuntu-latest
    uses: actions/cache@v2
    with:
      path: ~/.npm
      key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      restore-keys: |
        ${{ runner.os }}-node-
    steps:
      - name: Install dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: depth
    uses: jitterbit/get-changed-files@v1
    steps:
      - name: Formatting check
        run: npm run check:files -- steps.lint.outputs.added_modified

  build:
    runs-on: ubuntu-latest
    needs: depth
    steps:
      - name: Build
        run: npm run build
